Repository LM-channel-team-project/Team-Auto-Matcher, pull requests merged in 2021-07, with the labels that each got.

#45 Fix: Escape specific characters on RegExp
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.tsx
Labels: bug, frontend

#46 Feat: Change auth type based on the login status #41
  client/src/Apollo.ts
  client/src/App.tsx
  client/src/page/Dashboard/Team/index.tsx
Labels: frontend

#47 Fix: Remove repeated data
  client/src/component/orgamisms/DetailModal/Personal/index.tsx
Labels: frontend

#48 Feat: Add Result Page
  client/src/component/atoms/Button/index.stories.tsx
  client/src/component/atoms/Button/style.ts
  client/src/component/molecules/QuestionRespond/index.stories.tsx
  client/src/component/molecules/QuestionRespond/index.tsx
  client/src/component/molecules/QuestionRespond/style.ts
  client/src/component/orgamisms/QuestionResult/index.tsx
  client/src/component/orgamisms/QuestionResult/style.ts
  client/src/graphql/mutations.ts
  client/src/graphql/queries.ts
  client/src/page/Dashboard/Personal/index.tsx
  client/src/page/Dashboard/Personal/style.ts
  client/src/page/Dashboard/Team/index.tsx
  client/src/page/Result/index.tsx
  client/src/page/Result/style.ts
  client/src/page/Survey/index.tsx
Labels: frontend

#51 Fix: surveyCompleted props add
  client/src/page/Result/index.tsx
Labels: bug, frontend

#59 Fix loading component not popping error when logged in
  client/src/page/Home/index.tsx
Labels: bug

#60 반응형 및 confirm modal result page 적용
  client/src/component/atoms/Button/style.ts
  client/src/component/orgamisms/ConfirmModal/index.stories.tsx
  client/src/component/orgamisms/ConfirmModal/index.tsx
  client/src/component/orgamisms/ConfirmModal/style.ts
  client/src/component/orgamisms/DetailModal/Mail/index.tsx
  client/src/component/orgamisms/QuestionResult/index.tsx
  client/src/page/Dashboard/Personal/index.tsx
  client/src/page/Dashboard/Personal/style.ts
  client/src/page/Dashboard/Team/index.tsx
  client/src/page/Dashboard/Team/style.ts
  client/src/page/Mail/style.ts
  client/src/style/theme.ts
Labels: frontend

#61 [Fix]Contact page mail 주소 수정
  client/src/page/Contact/index.tsx
Labels: frontend

#62 모든 alert들을 모달창으로 바꿨습니다.
  client/src/component/orgamisms/ConfirmModal/index.tsx
  client/src/component/orgamisms/ConfirmModal/style.ts
  client/src/component/orgamisms/DetailModal/Mail/index.tsx
  client/src/component/orgamisms/DetailModal/Personal/index.tsx
  client/src/component/orgamisms/DetailModal/Team/index.tsx
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.tsx
  client/src/component/orgamisms/QuestionResult/index.tsx
  client/src/page/Contact/style.ts
  client/src/page/Dashboard/Personal/index.tsx
  client/src/page/Dashboard/Personal/style.ts
  client/src/page/Dashboard/Team/index.tsx
  client/src/page/Dashboard/Team/style.ts
  client/src/page/Home/index.tsx
  client/src/page/Mail/style.ts
Labels: frontend

#65 Feature/fix mail error
  client/src/component/orgamisms/DetailModal/Mail/index.tsx
  client/src/component/orgamisms/DetailModal/Personal/index.tsx
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.tsx
  client/src/component/orgamisms/DetailModal/style.ts
Labels: bug

#64 [fix] survey의 계획 프로젝트 항목이 업데이트 안되는 문제
  client/src/component/orgamisms/QuestionResult/index.tsx
Labels: bug, frontend

#66 몇가지 현상을 수정했습니다.
  client/src/component/orgamisms/DetailModal/Mail/index.tsx
  client/src/component/orgamisms/DetailModal/Personal/index.tsx
  client/src/component/orgamisms/DetailModal/Team/index.tsx
Labels: bug

#67 팀 생성하기 버튼과 설문 등록하기 버튼이 모바일에서 안 보이는 현상을 수정했습니다.
  client/src/component/orgamisms/QuestionResult/style.ts
  client/src/page/Dashboard/Team/style.ts
Labels: bug

#68 리드미 수정했습니다.
  README.md
Labels: documentation

#69 AWS Structure update
  README.md
Labels: documentation

#72 메일함에 로그인 직후 언디파인 에러 수정했습니다.
  client/src/component/orgamisms/DetailModal/Personal/index.tsx
  client/src/component/orgamisms/DetailModal/Team/index.tsx
  client/src/page/Dashboard/Personal/index.tsx
  client/src/page/Dashboard/Team/index.tsx
  client/src/page/Mail/index.tsx
Labels: bug
