Repository LM-channel-team-project/Team-Auto-Matcher, pull requests merged in 2021-09, with the labels that each got.

#166 팀페이지의 팀장명 혹은 개인의 팀명이 잘못 뜨는 현상을 수정했습니다.
  client/src/component/orgamisms/DetailModal/Personal/index.tsx
  client/src/component/orgamisms/DetailModal/Team/index.tsx
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.tsx
  client/src/page/Dashboard/Team/index.tsx
  client/src/utils/setTeamId.tsx
Labels: bug

#168 로그인 안한 상태에서 언디파인 에러를 수정했습니다.
  client/src/component/orgamisms/DetailModal/Personal/index.tsx
Labels: bug

#169 graphql api loading시 load Component 설정
  client/src/page/BaseTemplate/index.tsx
  client/src/page/BaseTemplate/style.ts
  client/src/page/Dashboard/Personal/index.tsx
  client/src/page/Dashboard/Personal/style.ts
  client/src/page/Dashboard/Team/index.tsx
  client/src/page/Dashboard/Team/style.ts
  client/src/page/Home/index.tsx
  client/src/page/Home/style.ts
  client/src/page/Loading/index.tsx
  client/src/page/Loading/style.ts
  client/src/page/Mail/index.tsx
  client/src/page/Mail/style.ts
  client/src/page/Notice/index.tsx
  client/src/page/Notice/style.ts
  client/src/page/Result/style.ts
  client/src/page/Survey/index.tsx
  client/src/page/Survey/style.ts
Labels: frontend

#179 쿼리와 뮤테이션을 더 직관적으로 import하도록 만들었습니다.
  client/package-lock.json
  client/src/component/orgamisms/DetailModal/Mail/index.tsx
  client/src/component/orgamisms/DetailModal/Notice/index.tsx
  client/src/component/orgamisms/DetailModal/NoticeAddForm/index.tsx
  client/src/component/orgamisms/DetailModal/Personal/index.tsx
  client/src/component/orgamisms/DetailModal/Team/index.tsx
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.tsx
  client/src/component/orgamisms/MenuBar/index.tsx
  client/src/component/orgamisms/QuestionResult/index.tsx
  client/src/graphql/mutations.ts
  client/src/graphql/queries.ts
  client/src/page/Dashboard/Personal/index.tsx
  client/src/page/Dashboard/Team/index.tsx
  client/src/page/Home/index.tsx
  client/src/page/Mail/index.tsx
  client/src/page/Notice/index.tsx
  client/src/page/Survey/index.tsx
Labels: 리팩토링

#178 result 관련 페이지 타입 분리
  client/src/component/molecules/QuestionRespond/index.tsx
  client/src/component/orgamisms/QuestionResult/index.tsx
  client/src/page/Result/index.tsx
  client/src/page/Survey/index.tsx
  client/src/types/index.ts
Labels: 리팩토링
