Repository LM-channel-team-project/Team-Auto-Matcher, pull requests merged in 2021-08, with the labels that each got.

#75 협업 경험(hasCoWork)이 반대값나오는 이슈
  client/src/component/orgamisms/QuestionResult/index.tsx
Labels: bug, frontend

#79 Feature/csspersonal
  client/src/page/Dashboard/Personal/index.tsx
  client/src/page/Dashboard/Personal/style.ts
Labels: frontend

#80 짧은 한 마디를 줄이고, 디스플레이적으로 몇 개 수정하였습니다. personState를 추가했습니다.
  client/src/component/molecules/MultiCheckbox/index.tsx
  client/src/component/orgamisms/DetailModal/Personal/index.stories.tsx
  client/src/component/orgamisms/DetailModal/Personal/index.tsx
  client/src/component/orgamisms/DetailModal/style.ts
  client/src/component/orgamisms/QuestionResult/index.tsx
  client/src/graphql/mutations.ts
  client/src/graphql/queries.ts
  client/src/page/Contact/style.ts
  client/src/page/Dashboard/Personal/index.tsx
  client/src/page/Dashboard/Personal/style.ts
  client/src/page/Dashboard/Team/style.ts
Labels: frontend

#86 Feature/add go back button in result page
  client/src/component/orgamisms/DetailModal/Mail/index.tsx
  client/src/component/orgamisms/DetailModal/Personal/index.tsx
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.tsx
  client/src/component/orgamisms/DetailModal/style.ts
  client/src/component/orgamisms/MenuBar/index.tsx
  client/src/component/orgamisms/QuestionResult/index.tsx
  client/src/component/orgamisms/QuestionResult/style.ts
  client/src/page/Dashboard/Team/index.tsx
  client/src/page/Home/index.tsx
  client/src/page/Login/index.tsx
  client/src/page/Mail/index.tsx
  client/src/page/Survey/index.tsx
Labels: bug, frontend

#87 window reload 를 history.go(0)으로 수정했습니다.
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.tsx
  client/src/component/orgamisms/MenuBar/index.tsx
  client/src/page/Login/index.tsx
Labels: frontend

#89 메일함 위에 메일 몇개가 왔는지 count를 추가 했습니다.
  client/src/component/orgamisms/MenuBar/index.tsx
  client/src/component/orgamisms/MenuBar/style.ts
Labels: frontend

#91 메일 화면과 홈 화면에서 로딩 스피너 중앙 정렬
  client/src/component/orgamisms/DetailModal/Mail/index.tsx
  client/src/component/orgamisms/DetailModal/style.ts
  client/src/component/orgamisms/MenuBar/index.tsx
  client/src/component/orgamisms/MenuBar/style.ts
  client/src/page/Home/index.tsx
  client/src/page/Home/style.ts
Labels: frontend

#92 메시지 카운터 undefined 나는 문제
  client/src/component/orgamisms/MenuBar/index.tsx
  client/src/component/orgamisms/MenuBar/style.ts
Labels: bug, frontend

#94 팀이나 사용자가 삭제 될 경우 null 에러
  client/src/component/orgamisms/DetailModal/Mail/index.tsx
Labels: bug, frontend

#98 person table 삭제하고 userTable과 합쳤습니다.
  client/src/Apollo.ts
  client/src/component/orgamisms/DetailModal/Mail/index.tsx
  client/src/component/orgamisms/DetailModal/Personal/index.stories.tsx
  client/src/component/orgamisms/DetailModal/Personal/index.tsx
  client/src/component/orgamisms/DetailModal/Team/index.stories.tsx
  client/src/component/orgamisms/DetailModal/Team/index.tsx
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.stories.tsx
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.tsx
  client/src/component/orgamisms/DetailModal/template/index.tsx
  client/src/component/orgamisms/MenuBar/index.tsx
  client/src/component/orgamisms/QuestionResult/index.tsx
  client/src/graphql/mutations.ts
  client/src/graphql/queries.ts
  client/src/page/Dashboard/Personal/index.tsx
  client/src/page/Dashboard/Personal/style.ts
  client/src/page/Dashboard/Team/index.tsx
  client/src/page/Login/index.tsx
  client/src/page/Survey/index.tsx
Labels: frontend

#107 route에서 warning 메시지가 뜨는 것을 수정했습니다.
  client/src/App.tsx
Labels: bug

#113 survey completed가 false일 때에도 코드에 의해 아무것도 없는 화면을 나타내는 현상을 수정하였습니다.
  client/src/page/Dashboard/Personal/index.tsx
Labels: bug

#111 팀 나가기 버튼과 팀 내보내기 버튼 구현했습니다.
  client/src/component/orgamisms/DetailModal/Personal/index.tsx
  client/src/component/orgamisms/DetailModal/Team/index.tsx
Labels: frontend

#114 팀이 1개일 때 팀 구하는 중이라고 뜨는 현상을 수정했습니다.
  client/src/page/Dashboard/Personal/index.tsx
Labels: bug

#117 공지사항 탭을 추가하였습니다.
  client/src/Apollo.ts
  client/src/App.tsx
  client/src/component/molecules/DetailContent/index.tsx
  client/src/component/orgamisms/DetailModal/Notice/index.stories.tsx
  client/src/component/orgamisms/DetailModal/Notice/index.tsx
  client/src/component/orgamisms/DetailModal/NoticeAddForm/index.stories.tsx
  client/src/component/orgamisms/DetailModal/NoticeAddForm/index.tsx
  client/src/component/orgamisms/DetailModal/Personal/index.tsx
  client/src/component/orgamisms/DetailModal/Team/index.tsx
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.tsx
  client/src/component/orgamisms/DetailModal/style.ts
  client/src/component/orgamisms/MenuBar/index.tsx
  client/src/component/orgamisms/MenuBar/style.ts
  client/src/graphql/mutations.ts
  client/src/graphql/queries.ts
  client/src/page/Home/index.tsx
  client/src/page/Mail/index.tsx
  client/src/page/Notice/index.tsx
  client/src/page/Notice/style.ts
  client/src/page/Survey/index.tsx
Labels: frontend

#124 로그인 없이 팀 디테일 들어갈 때 언디파인 에러 수정했습니다.
  client/src/component/orgamisms/DetailModal/Team/index.tsx
Labels: bug

#125 공지사항 만들 때 수정하지 못한 부분 재수정해서 올려드립니다.
  client/src/component/orgamisms/DetailModal/Notice/index.tsx
  client/src/component/orgamisms/DetailModal/NoticeAddForm/index.tsx
Labels: frontend

#129 팀 생성일과 회원가입일을 추가했습니다.
  client/src/component/orgamisms/DetailModal/Notice/index.stories.tsx
  client/src/component/orgamisms/DetailModal/Notice/index.tsx
  client/src/component/orgamisms/DetailModal/NoticeAddForm/index.tsx
  client/src/component/orgamisms/DetailModal/Team/index.stories.tsx
  client/src/component/orgamisms/DetailModal/Team/index.tsx
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.stories.tsx
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.tsx
  client/src/graphql/mutations.ts
  client/src/graphql/queries.ts
  client/src/page/Dashboard/Personal/index.tsx
  client/src/page/Dashboard/Personal/style.ts
  client/src/page/Dashboard/Team/index.tsx
  client/src/page/Dashboard/Team/style.ts
  client/src/page/Mail/index.tsx
  client/src/page/Mail/style.ts
  client/src/page/Notice/index.tsx
  client/src/page/Notice/style.ts
  client/src/page/Survey/index.tsx
  client/src/page/Survey/style.ts
Labels: frontend

#135 깃 허브 API로 team detail modal에 표시
  client/package-lock.json
  client/package.json
  client/src/component/orgamisms/DetailModal/Team/index.stories.tsx
  client/src/component/orgamisms/DetailModal/Team/index.tsx
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.stories.tsx
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.tsx
  client/src/component/orgamisms/DetailModal/style.ts
  client/src/component/orgamisms/DetailModal/template/style.ts
  client/src/graphql/mutations.ts
  client/src/graphql/queries.ts
Labels: frontend

#136 메일 보낸 날짜를 추가했습니다.
  client/src/component/orgamisms/DetailModal/Mail/index.stories.tsx
  client/src/component/orgamisms/DetailModal/Mail/index.tsx
  client/src/component/orgamisms/DetailModal/Notice/index.tsx
  client/src/component/orgamisms/DetailModal/Personal/index.stories.tsx
  client/src/component/orgamisms/DetailModal/Personal/index.tsx
  client/src/component/orgamisms/DetailModal/Team/index.tsx
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.stories.tsx
  client/src/component/orgamisms/DetailModal/template/index.tsx
  client/src/graphql/mutations.ts
  client/src/graphql/queries.ts
  client/src/page/Mail/index.tsx
  client/src/page/Notice/index.tsx
  client/src/utils/date.tsx
Labels: frontend

#140 로그인했을 시에도 모달창이 나오는 것을 수정하였습니다.
  client/package.json
  client/src/App.tsx
  client/src/page/Dashboard/Personal/style.ts
  client/src/page/Login/index.tsx
  client/src/page/Mail/index.tsx
  client/src/page/Result/index.tsx
  client/src/page/Result/style.ts
  client/src/page/Survey/index.tsx
Labels: bug

#144 eslint warning 수정하였습니다.
  client/src/component/atoms/Button/index.stories.tsx
  client/src/component/atoms/ProgressBarList/index.stories.tsx
  client/src/component/molecules/ArrowNav/index.stories.tsx
  client/src/component/molecules/DirectionNav/index.stories.tsx
  client/src/component/molecules/LoginBtn/index.stories.tsx
  client/src/component/molecules/OAuthLogin/index.stories.tsx
  client/src/component/molecules/ProgressBar/index.stories.tsx
  client/src/component/orgamisms/AutoCompleteList/index.stories.tsx
  client/src/component/orgamisms/DetailModal/Mail/index.stories.tsx
  client/src/component/orgamisms/DetailModal/Notice/index.stories.tsx
  client/src/component/orgamisms/DetailModal/NoticeAddForm/index.stories.tsx
  client/src/component/orgamisms/DetailModal/Personal/index.stories.tsx
  client/src/component/orgamisms/DetailModal/Team/index.stories.tsx
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.stories.tsx
  client/src/component/orgamisms/Questionnaire/index.stories.tsx
Labels: bug

#148 로그인 안한 상태에서 언디파인 에러 수정하였습니다.
  client/src/page/Survey/index.tsx
Labels: bug

#161 git api limit 해제
  client/src/component/orgamisms/DetailModal/Team/index.tsx
Labels: bug

#165 홈버튼이 햄버거 바에서 route 경로가 잘못 설정된 것을 수정하였습니다.
  client/src/component/orgamisms/MenuBar/index.tsx
Labels: frontend

#164 댓글 기능 추가하였습니다.
  client/src/component/orgamisms/CommentInputBox/index.stories.tsx
  client/src/component/orgamisms/CommentInputBox/index.tsx
  client/src/component/orgamisms/CommentInputBox/style.ts
  client/src/component/orgamisms/DetailModal/Mail/index.tsx
  client/src/component/orgamisms/DetailModal/Personal/index.tsx
  client/src/component/orgamisms/DetailModal/Team/index.stories.tsx
  client/src/component/orgamisms/DetailModal/Team/index.tsx
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.stories.tsx
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.tsx
  client/src/component/orgamisms/DetailModal/style.ts
  client/src/component/orgamisms/DetailModal/template/index.tsx
  client/src/graphql/mutations.ts
  client/src/graphql/queries.ts
Labels: frontend

#167 팀 정보를 업데이트 확정을 하고 나서 디테일 모달이 닫히던 것을 닫히지 않게 수정하였습니다.
  client/src/component/orgamisms/DetailModal/TeamAddForm/index.tsx
Labels: frontend
